"""Shared helpers for CAI AMP scripts."""

from __future__ import annotations

import json
import os
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from cai.lib.paths import CONFIG_DIR, ENDPOINTS_ENV, NIM_ENDPOINTS_JSON, ensure_cai_dirs


def load_dotenv_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def write_dotenv_file(path: Path, values: dict[str, str]) -> None:
    ensure_cai_dirs()
    lines = ["# Generated by CAI AMP wiring — do not edit manually"]
    for key in sorted(values):
        lines.append(f'{key}="{values[key]}"')
    path.write_text("\n".join(lines) + "\n")


def apply_dotenv_to_os(path: Path) -> dict[str, str]:
    values = load_dotenv_file(path)
    os.environ.update(values)
    return values


def run_cmd(cmd: list[str] | str, *, cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    if isinstance(cmd, str):
        return subprocess.run(cmd, shell=True, cwd=cwd, check=check, text=True)
    return subprocess.run(cmd, cwd=cwd, check=check, text=True)


def wait_for_http(url: str, *, timeout_s: int = 600, interval_s: int = 5) -> None:
    deadline = time.time() + timeout_s
    last_error = ""
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=10) as response:
                if response.status < 500:
                    return
        except Exception as exc:  # noqa: BLE001
            last_error = str(exc)
        time.sleep(interval_s)
    raise TimeoutError(f"Timed out waiting for {url}: {last_error}")


def merge_nim_endpoints(update: dict[str, Any]) -> dict[str, Any]:
    ensure_cai_dirs()
    data: dict[str, Any] = {}
    if NIM_ENDPOINTS_JSON.exists():
        data = json.loads(NIM_ENDPOINTS_JSON.read_text())
    data.update(update)
    NIM_ENDPOINTS_JSON.write_text(json.dumps(data, indent=2) + "\n")
    return data


def get_ray_head_url() -> str:
    domain = os.environ.get("CDSW_DOMAIN") or os.environ.get("CML_HOST", "").replace("https://", "").replace("http://", "")
    head_app = os.environ.get("RAY_HEAD_APP_NAME", "content-localization-ray-head")
    if not domain:
        raise RuntimeError("CDSW_DOMAIN or CML_HOST must be set")
    return f"https://{head_app}.{domain}"


def load_runtime_endpoints() -> dict[str, str]:
    if ENDPOINTS_ENV.exists():
        return load_dotenv_file(ENDPOINTS_ENV)
    return {}
